/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetreconnaissancefaciale.Vues;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import projetreconnaissancefaciale.Controleurs.InscriHandler;
import projetreconnaissancefaciale.Controleurs.OpenCVFaceRecognizer;
import projetreconnaissancefaciale.Controleurs.ParamUserHandler;
import projetreconnaissancefaciale.Controleurs.prendrePhotoHandler;
import projetreconnaissancefaciale.Modeles.ParamUserModel;

/**
 *
 * @author Alexis
 */
public class ApresConnectionView extends javax.swing.JFrame {

    /**
     * Creates new form ApresConnectionView
     */
    public ApresConnectionView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelProfil = new javax.swing.JPanel();
        labTitre5 = new javax.swing.JLabel();
        labProfilNom = new javax.swing.JLabel();
        labProfilDateNaiss = new javax.swing.JLabel();
        labProfilInfo = new javax.swing.JLabel();
        labProfilImage = new javax.swing.JLabel();
        labProfilVille = new javax.swing.JLabel();
        labProfilPays = new javax.swing.JLabel();
        labelPhoto = new javax.swing.JLabel();
        butAnnuler5 = new javax.swing.JButton();
        panelRecherche = new javax.swing.JPanel();
        labTitre3 = new javax.swing.JLabel();
        butAnnuler3 = new javax.swing.JButton();
        fileChooseRecherche = new javax.swing.JFileChooser();
        labImaRecherche = new javax.swing.JLabel();
        butValider1 = new javax.swing.JButton();
        panelAjout = new javax.swing.JPanel();
        labTitre1 = new javax.swing.JLabel();
        butAnnuler = new javax.swing.JButton();
        butValider = new javax.swing.JButton();
        takePhoto = new javax.swing.JToggleButton();
        clear = new javax.swing.JToggleButton();
        photo = new javax.swing.JLabel();
        panelModif = new javax.swing.JPanel();
        labTitre2 = new javax.swing.JLabel();
        fileChoose = new javax.swing.JFileChooser();
        labIma = new javax.swing.JLabel();
        butAnnuler4 = new javax.swing.JButton();
        butValider2 = new javax.swing.JButton();
        panelParam = new javax.swing.JPanel();
        labTitre4 = new javax.swing.JLabel();
        butAnnuler2 = new javax.swing.JButton();
        butValider3 = new javax.swing.JButton();
        labNom = new javax.swing.JLabel();
        labPrenom = new javax.swing.JLabel();
        labMDP1 = new javax.swing.JLabel();
        labMDP2 = new javax.swing.JLabel();
        labMDP3 = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        textMDP1 = new javax.swing.JPasswordField();
        textMDP3 = new javax.swing.JPasswordField();
        textMDP2 = new javax.swing.JPasswordField();
        labParamDateNaiss = new javax.swing.JLabel();
        labParamVille = new javax.swing.JLabel();
        labParamPays = new javax.swing.JLabel();
        textParamVille = new javax.swing.JTextField();
        textParamPays = new javax.swing.JTextField();
        labParamInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textParamInfo = new javax.swing.JTextArea();
        butModifMdp = new javax.swing.JButton();
        labErreurMdp = new javax.swing.JLabel();
        textParamDateNaiss = new com.toedter.calendar.JDateChooser();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(720, 520));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(710, 510));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        panelProfil.setBackground(new java.awt.Color(227, 227, 227));
        panelProfil.setPreferredSize(new java.awt.Dimension(700, 500));

        labTitre5.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre5.setForeground(new java.awt.Color(62, 96, 111));
        labTitre5.setText("RecoFace");

        labProfilNom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labProfilNom.setText("Bienvenue Nom Prenom");

        labProfilDateNaiss.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labProfilDateNaiss.setText("Né(e) le :  ");

        labProfilInfo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labProfilInfo.setText("Informations :");

        labProfilVille.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labProfilVille.setText("Ville :");

        labProfilPays.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labProfilPays.setText("Pays :");

        labelPhoto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        butAnnuler5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butAnnuler5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butAnnuler5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAnnuler5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labProfilDateNaiss)
                    .addComponent(labProfilVille)
                    .addComponent(labProfilPays)
                    .addComponent(labProfilInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(labProfilImage))
                    .addComponent(labProfilNom)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilLayout.createSequentialGroup()
                        .addComponent(labTitre5)
                        .addGap(188, 188, 188)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panelProfilLayout.setVerticalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addComponent(labTitre5)
                .addGap(18, 18, 18)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(labProfilDateNaiss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labProfilVille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labProfilPays)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProfilLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(labProfilImage))
                            .addGroup(panelProfilLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labProfilInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(butAnnuler5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(labProfilNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Mon Profil", panelProfil);

        labTitre3.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre3.setForeground(new java.awt.Color(62, 96, 111));
        labTitre3.setText("RecoFace");

        butAnnuler3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butAnnuler3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butAnnuler3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler3ActionPerformed(evt);
            }
        });

        fileChooseRecherche.setFileFilter(new FileNameExtensionFilter(".jpg","jpg"));
        fileChooseRecherche.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fileChooseRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseRechercheActionPerformed(evt);
            }
        });

        labImaRecherche.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labImaRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labImaRechercheMouseClicked(evt);
            }
        });

        butValider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butValider1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butValider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butValider1MouseClicked(evt);
            }
        });
        butValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRechercheLayout = new javax.swing.GroupLayout(panelRecherche);
        panelRecherche.setLayout(panelRechercheLayout);
        panelRechercheLayout.setHorizontalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(fileChooseRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(labImaRecherche))
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(labTitre3)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panelRechercheLayout.setVerticalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValider1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRechercheLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(labImaRecherche))
                            .addComponent(labTitre3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileChooseRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rechercher un utilisateur", panelRecherche);

        panelAjout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAjout.setPreferredSize(new java.awt.Dimension(600, 475));
        panelAjout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAjoutMouseClicked(evt);
            }
        });
        panelAjout.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                panelAjoutComponentHidden(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                panelAjoutComponentShown(evt);
            }
        });

        labTitre1.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre1.setForeground(new java.awt.Color(62, 96, 111));
        labTitre1.setText("RecoFace");

        butAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        butAnnuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        butValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        butValider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butValiderMouseClicked(evt);
            }
        });
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        takePhoto.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        takePhoto.setText("Prendre une photo");
        takePhoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        takePhoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                takePhotoMouseClicked(evt);
            }
        });
        takePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takePhotoActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        clear.setText("Recommencer");
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });

        photo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panelAjoutLayout = new javax.swing.GroupLayout(panelAjout);
        panelAjout.setLayout(panelAjoutLayout);
        panelAjoutLayout.setHorizontalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(takePhoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clear)
                .addGap(88, 88, 88)
                .addComponent(butValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                        .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                        .addComponent(labTitre1)
                        .addGap(251, 251, 251))))
        );
        panelAjoutLayout.setVerticalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                .addComponent(labTitre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butValider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAnnuler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takePhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Prendre une photo de profil", panelAjout);

        panelModif.setPreferredSize(new java.awt.Dimension(504, 445));

        labTitre2.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre2.setForeground(new java.awt.Color(62, 96, 111));
        labTitre2.setText("RecoFace");

        fileChoose.setFileFilter(new FileNameExtensionFilter(".jpg","jpg"));
        fileChoose.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        fileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseActionPerformed(evt);
            }
        });

        labIma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labIma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labImaMouseClicked(evt);
            }
        });

        butAnnuler4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butAnnuler4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butAnnuler4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler4ActionPerformed(evt);
            }
        });

        butValider2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butValider2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butValider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModifLayout = new javax.swing.GroupLayout(panelModif);
        panelModif.setLayout(panelModifLayout);
        panelModifLayout.setHorizontalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGroup(panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(labTitre2))
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(labIma))
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelModifLayout.setVerticalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModifLayout.createSequentialGroup()
                .addGroup(panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butValider2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addComponent(labTitre2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(labIma)
                        .addGap(18, 18, 18)
                        .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("choisir une photo de profil", panelModif);

        panelParam.setPreferredSize(new java.awt.Dimension(700, 500));

        labTitre4.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre4.setForeground(new java.awt.Color(62, 96, 111));
        labTitre4.setText("RecoFace");

        butAnnuler2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butAnnuler2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butAnnuler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler2ActionPerformed(evt);
            }
        });

        butValider3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butValider3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butValider3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider3ActionPerformed(evt);
            }
        });

        labNom.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labNom.setText("Nom :");

        labPrenom.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labPrenom.setText("Prénom :");

        labMDP1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labMDP1.setText("Ancien mot de passe :");

        labMDP2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labMDP2.setText("Nouveau mot de passe :");

        labMDP3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labMDP3.setText("Nouveau mot de passe :");

        labParamDateNaiss.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labParamDateNaiss.setText("Date de Naissance :");

        labParamVille.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labParamVille.setText("Ville :");

        labParamPays.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labParamPays.setText("Pays :");

        labParamInfo.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labParamInfo.setText("Informations :");

        textParamInfo.setColumns(20);
        textParamInfo.setRows(5);
        jScrollPane1.setViewportView(textParamInfo);

        butModifMdp.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        butModifMdp.setText("Modifier le mot de passe");
        butModifMdp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        butModifMdp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        butModifMdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butModifMdpActionPerformed(evt);
            }
        });

        labErreurMdp.setForeground(new java.awt.Color(255, 51, 51));
        labErreurMdp.setText("Erreur mot de passe");

        javax.swing.GroupLayout panelParamLayout = new javax.swing.GroupLayout(panelParam);
        panelParam.setLayout(panelParamLayout);
        panelParamLayout.setHorizontalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParamLayout.createSequentialGroup()
                                .addComponent(labParamInfo)
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelParamLayout.createSequentialGroup()
                                    .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labParamDateNaiss)
                                        .addComponent(labParamVille)
                                        .addComponent(labParamPays)
                                        .addComponent(labNom))
                                    .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelParamLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelParamLayout.createSequentialGroup()
                                                    .addComponent(textParamPays, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                                                    .addComponent(butModifMdp))
                                                .addGroup(panelParamLayout.createSequentialGroup()
                                                    .addComponent(textParamVille, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(labErreurMdp)
                                                    .addGap(41, 41, 41))))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParamLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(panelParamLayout.createSequentialGroup()
                                                    .addComponent(labMDP2)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(textMDP2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelParamLayout.createSequentialGroup()
                                                    .addComponent(labMDP3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(textMDP3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(panelParamLayout.createSequentialGroup()
                                                    .addComponent(labMDP1)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(textMDP1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(panelParamLayout.createSequentialGroup()
                                    .addComponent(labPrenom)
                                    .addGap(100, 100, 100)
                                    .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(textParamDateNaiss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(textNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(panelParamLayout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(labTitre4)))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValider3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        panelParamLayout.setVerticalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParamLayout.createSequentialGroup()
                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butValider3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addComponent(labTitre4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNom)
                            .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labMDP1)
                            .addComponent(textMDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMDP2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labPrenom)
                                .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labMDP2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labMDP3)
                                .addComponent(textMDP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labParamDateNaiss)
                            .addComponent(textParamDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamVille)
                            .addComponent(textParamVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labErreurMdp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamPays)
                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(textParamPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(butModifMdp)))
                        .addGap(26, 26, 26)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamInfo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Paramètres", panelParam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnulerActionPerformed

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
        //prend une photo
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnuler3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler3ActionPerformed

    private void labImaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labImaMouseClicked
        labIma.setIcon(null);
        fileChoose.setVisible(true);
    }//GEN-LAST:event_labImaMouseClicked

    private void fileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseActionPerformed
        fileChoose.setVisible(false);
        File selection = fileChoose.getSelectedFile();
        fileChoose.setSelectedFile(null);
        String completeFileName = selection.getAbsolutePath();

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(completeFileName).getScaledInstance(300, 300, Image.SCALE_DEFAULT));
        labIma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labIma.setVerticalAlignment(javax.swing.SwingConstants.CENTER); 
        labIma.setIcon(icon);
    }//GEN-LAST:event_fileChooseActionPerformed

    private void butAnnuler4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler4ActionPerformed

    private void fileChooseRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseRechercheActionPerformed
        fileChooseRecherche.setVisible(false);
        File selection = fileChooseRecherche.getSelectedFile();
        fileChooseRecherche.setSelectedFile(null);
        String completeFileName = selection.getAbsolutePath();

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(completeFileName).getScaledInstance(300, 300, Image.SCALE_DEFAULT));
        labImaRecherche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labImaRecherche.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        labImaRecherche.setIcon(icon);
    }//GEN-LAST:event_fileChooseRechercheActionPerformed

    private void labImaRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labImaRechercheMouseClicked
        labImaRecherche.setIcon(null);
        fileChooseRecherche.setVisible(true);
    }//GEN-LAST:event_labImaRechercheMouseClicked

    private void butValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butValider1ActionPerformed

    private void butValider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butValider2ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        try {
            ParamUserHandler.RechercheInfoUser();
            //Mis à jour de l'image de profil
            
            ImageIcon imgProfil = new ImageIcon(Toolkit.getDefaultToolkit().getImage("img/userface/User_" + ParamUserHandler.getLogin() + ".jpg").getScaledInstance(300, 300, Image.SCALE_DEFAULT));
            labelPhoto.setIcon(imgProfil);
            
            
            textNom.setText(ParamUserHandler.getUserNom().toUpperCase());
            textPrenom.setText(ParamUserHandler.getUserPrenom());
            String s = ParamUserHandler.getUserDateNaiss();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dateNaissBDD = sdf.parse(s);
            
            textParamDateNaiss.setDate(dateNaissBDD);
            textParamVille.setText(ParamUserHandler.getUserVille().toUpperCase());
            textParamPays.setText(ParamUserHandler.getUserPays().toUpperCase());
            textParamInfo.setText(ParamUserHandler.getUserInfo());
            labProfilNom.setText("");
            labProfilNom.setText("Bienvenue " + ParamUserHandler.getUserPrenom().toString() + " " + ParamUserHandler.getUserNom().toString().toUpperCase());
            labProfilDateNaiss.setText("");

            labProfilDateNaiss.setText("Né(e) le : " + ParamUserHandler.AjoutDateUStoFR(dateNaissBDD));

            labProfilVille.setText("");
            labProfilVille.setText("Ville : " + ParamUserHandler.getUserVille().toString());
            labProfilPays.setText("");
            labProfilPays.setText("Pays : " + ParamUserHandler.getUserPays().toString().toUpperCase());
            labProfilInfo.setText("");
            labProfilInfo.setText("Informations : " + ParamUserHandler.getUserInfo().toString());
        } catch (ParseException ex) {
            Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ImageIcon imgProfil = new ImageIcon(Toolkit.getDefaultToolkit().getImage("img/userface/User_" + ParamUserHandler.getLogin() + ".jpg").getScaledInstance(300, 300, Image.SCALE_DEFAULT));
        labelPhoto.setIcon(imgProfil);
        ParamUserHandler.RechercheInfoUser();
        labErreurMdp.setVisible(false);
        labMDP1.setVisible(false);
        labMDP2.setVisible(false);
        labMDP3.setVisible(false);
        textMDP1.setVisible(false);
        textMDP2.setVisible(false);
        textMDP3.setVisible(false);

        labProfilNom.setText("");
        labProfilNom.setText("Bienvenue " + ParamUserHandler.getUserPrenom().toString() + " " + ParamUserHandler.getUserNom().toString().toUpperCase());
        labProfilDateNaiss.setText("");
        try {
            String s = ParamUserHandler.getUserDateNaiss();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date dateNaissBDD = sdf.parse(s);
            labProfilDateNaiss.setText("Né(e) le : " + ParamUserHandler.AjoutDateUStoFR(dateNaissBDD));
        } catch (ParseException ex) {
            Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
        }
        labProfilVille.setText("");
        labProfilVille.setText("Ville : " + ParamUserHandler.getUserVille().toString());
        labProfilPays.setText("");
        labProfilPays.setText("Pays : " + ParamUserHandler.getUserPays().toString().toUpperCase());
        labProfilInfo.setText("");
        labProfilInfo.setText("Informations : " + ParamUserHandler.getUserInfo().toString());

    }//GEN-LAST:event_formWindowActivated

    private void butValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butValiderMouseClicked

        if (prendrePhotoHandler.verificationPhoto(ParamUserHandler.getLogin()) == false) {
            new apresPhotoView().setVisible(true);
        } else {
            prendrePhotoHandler.sauvegardePhoto(ParamUserHandler.getLogin());

            if (prendrePhotoHandler.verificationPhoto(ParamUserHandler.getLogin()) == false) {
                new apresPhotoView().setVisible(true);
            } else {
                new apresPhotoValidationView().setVisible(true);

            };

    }//GEN-LAST:event_butValiderMouseClicked
    }
    private void panelAjoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAjoutMouseClicked
    }//GEN-LAST:event_panelAjoutMouseClicked

    private void panelAjoutComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelAjoutComponentShown
        takePhoto.setEnabled(true);
        clear.setEnabled(false);
        prendrePhotoHandler ab = new prendrePhotoHandler(photo);
        Thread th = new Thread(ab);
        ab.start();
    }//GEN-LAST:event_panelAjoutComponentShown

    private void takePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_takePhotoActionPerformed

    private void takePhotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_takePhotoMouseClicked
        prendrePhotoHandler ab = new prendrePhotoHandler(photo);
        Thread w = new Thread(ab);
        ab.stop();
        takePhoto.setEnabled(false);
        clear.setEnabled(true);
    }//GEN-LAST:event_takePhotoMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
        takePhoto.setEnabled(true);
        clear.setEnabled(false);
        prendrePhotoHandler ab = new prendrePhotoHandler(photo);

        Thread th = new Thread(ab);
        ab.start();
    }//GEN-LAST:event_clearMouseClicked

    private void panelAjoutComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelAjoutComponentHidden
        prendrePhotoHandler ab = new prendrePhotoHandler(photo);
        Thread th = new Thread(ab);
        ab.stop();
    }//GEN-LAST:event_panelAjoutComponentHidden

    private void butValider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butValider1MouseClicked
        int i = OpenCVFaceRecognizer.comparaison("img/temporyFace/test.jpg");
        try {
            String[] s = ParamUserModel.getUserWithId(i);
            System.out.println(s[1]);
        } catch (SQLException ex) {
            Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butValider1MouseClicked

    private void butModifMdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butModifMdpActionPerformed
        if (labMDP1.isVisible()) {
            labMDP1.setVisible(false);
            labMDP2.setVisible(false);
            labMDP3.setVisible(false);
            textMDP1.setVisible(false);
            textMDP2.setVisible(false);
            textMDP3.setVisible(false);
            labErreurMdp.setVisible(false);
        } else {
            labMDP1.setVisible(true);
            labMDP2.setVisible(true);
            labMDP3.setVisible(true);
            textMDP1.setVisible(true);
            textMDP2.setVisible(true);
            textMDP3.setVisible(true);
        }
    }//GEN-LAST:event_butModifMdpActionPerformed

    private void butValider3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider3ActionPerformed
        try {
            String mdp1 = textMDP1.getText().toString();
            String mdp2 = textMDP2.getText().toString();
            String mdp3 = textMDP3.getText().toString();
            Date datePick = textParamDateNaiss.getDate();
            String dateNaiss = ParamUserHandler.AjoutDateFRtoUS(datePick);
            String nom = textNom.getText().toUpperCase().toString();
            String prenom = textPrenom.getText().toString();
            String ville = textParamVille.getText().toUpperCase().toString();
            String pays = textParamPays.getText().toUpperCase().toString();
            String remarque = textParamInfo.getText().toString();
            String mail = ParamUserHandler.getLogin().toString();

            if (textMDP1.isVisible()) {
                if ((mdp1.matches("")) || (mdp2.matches("")) || (mdp3.matches(""))) {
                    labErreurMdp.setVisible(true);
                    return;
                } else {

                    try {
                        if (ParamUserHandler.Valider(mdp1, mdp2, mdp3)) {
                            System.out.println("Bien pour les mots de passe dans paramètres");
                        } else {
                            System.out.println("Pas bien pour les mots de passe dans paramètres");
                            return;
                        }
                        if (InscriHandler.isValid(1, textNom.getText()) == false) {
                            return;
                        }

                        if (InscriHandler.isValid(1, textPrenom.getText()) == false) {
                            return;
                        }

                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    ParamUserHandler.envoiInscription(1, nom, prenom, mail, mdp2, dateNaiss, ville, pays, remarque);
                }
            } else {
                ParamUserHandler.envoiInscription(2, nom, prenom, mail, mdp2, dateNaiss, ville, pays, remarque);
            }

        } catch (ParseException ex) {
            Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butValider3ActionPerformed

    private void butAnnuler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler2ActionPerformed

    private void butAnnuler5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresConnectionView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butAnnuler2;
    private javax.swing.JButton butAnnuler3;
    private javax.swing.JButton butAnnuler4;
    private javax.swing.JButton butAnnuler5;
    private javax.swing.JButton butModifMdp;
    private javax.swing.JButton butValider;
    private javax.swing.JButton butValider1;
    private javax.swing.JButton butValider2;
    private javax.swing.JButton butValider3;
    private javax.swing.JToggleButton clear;
    private javax.swing.JFileChooser fileChoose;
    private javax.swing.JFileChooser fileChooseRecherche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel labErreurMdp;
    private javax.swing.JLabel labIma;
    private javax.swing.JLabel labImaRecherche;
    private javax.swing.JLabel labMDP1;
    private javax.swing.JLabel labMDP2;
    private javax.swing.JLabel labMDP3;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labParamDateNaiss;
    private javax.swing.JLabel labParamInfo;
    private javax.swing.JLabel labParamPays;
    private javax.swing.JLabel labParamVille;
    private javax.swing.JLabel labPrenom;
    private javax.swing.JLabel labProfilDateNaiss;
    private javax.swing.JLabel labProfilImage;
    private javax.swing.JLabel labProfilInfo;
    private javax.swing.JLabel labProfilNom;
    private javax.swing.JLabel labProfilPays;
    private javax.swing.JLabel labProfilVille;
    private javax.swing.JLabel labTitre1;
    private javax.swing.JLabel labTitre2;
    private javax.swing.JLabel labTitre3;
    private javax.swing.JLabel labTitre4;
    private javax.swing.JLabel labTitre5;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JPanel panelAjout;
    private javax.swing.JPanel panelModif;
    private javax.swing.JPanel panelParam;
    private javax.swing.JPanel panelProfil;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JLabel photo;
    private javax.swing.JToggleButton takePhoto;
    private javax.swing.JPasswordField textMDP1;
    private javax.swing.JPasswordField textMDP2;
    private javax.swing.JPasswordField textMDP3;
    private javax.swing.JTextField textNom;
    private com.toedter.calendar.JDateChooser textParamDateNaiss;
    private javax.swing.JTextArea textParamInfo;
    private javax.swing.JTextField textParamPays;
    private javax.swing.JTextField textParamVille;
    private javax.swing.JTextField textPrenom;
    // End of variables declaration//GEN-END:variables
}
