/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetreconnaissancefaciale.Vues;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Alexis
 */
public class ApresConnectionView extends javax.swing.JFrame {

    /**
     * Creates new form ApresConnectionView
     */
    public ApresConnectionView() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelRecherche = new javax.swing.JPanel();
        labTitre3 = new javax.swing.JLabel();
        butAnnuler3 = new javax.swing.JButton();
        panelAjout = new javax.swing.JPanel();
        labTitre1 = new javax.swing.JLabel();
        butAnnuler = new javax.swing.JButton();
        butValider = new javax.swing.JButton();
        panelModif = new javax.swing.JPanel();
        labTitre2 = new javax.swing.JLabel();
        fileChoose = new javax.swing.JFileChooser();
        labIma = new javax.swing.JLabel();
        butAnnuler4 = new javax.swing.JButton();
        panelParam = new javax.swing.JPanel();
        labTitre4 = new javax.swing.JLabel();
        butAnnuler2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 475));
        setResizable(false);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(570, 463));

        labTitre3.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre3.setForeground(new java.awt.Color(62, 96, 111));
        labTitre3.setText("RecoFace");

        butAnnuler3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRechercheLayout = new javax.swing.GroupLayout(panelRecherche);
        panelRecherche.setLayout(panelRechercheLayout);
        panelRechercheLayout.setHorizontalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRechercheLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(labTitre3)
                .addGap(203, 203, 203))
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRechercheLayout.setVerticalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitre3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Rechercher un utilisateur", panelRecherche);

        labTitre1.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre1.setForeground(new java.awt.Color(62, 96, 111));
        labTitre1.setText("RecoFace");

        butAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        butValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAjoutLayout = new javax.swing.GroupLayout(panelAjout);
        panelAjout.setLayout(panelAjoutLayout);
        panelAjoutLayout.setHorizontalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(labTitre1)
                .addGap(203, 203, 203))
        );
        panelAjoutLayout.setVerticalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                .addGroup(panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );

        jTabbedPane1.addTab("Prendre une photo", panelAjout);

        panelModif.setPreferredSize(new java.awt.Dimension(504, 445));

        labTitre2.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre2.setForeground(new java.awt.Color(62, 96, 111));
        labTitre2.setText("RecoFace");

        fileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseActionPerformed(evt);
            }
        });

        labIma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labImaMouseClicked(evt);
            }
        });

        butAnnuler4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModifLayout = new javax.swing.GroupLayout(panelModif);
        panelModif.setLayout(panelModifLayout);
        panelModifLayout.setHorizontalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModifLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTitre2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelModifLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(labIma)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelModifLayout.setVerticalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModifLayout.createSequentialGroup()
                .addComponent(labTitre2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labIma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Modification de photo", panelModif);

        labTitre4.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre4.setForeground(new java.awt.Color(62, 96, 111));
        labTitre4.setText("RecoFace");

        butAnnuler2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelParamLayout = new javax.swing.GroupLayout(panelParam);
        panelParam.setLayout(panelParamLayout);
        panelParamLayout.setHorizontalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParamLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(labTitre4)
                .addGap(203, 203, 203))
            .addGroup(panelParamLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelParamLayout.setVerticalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTitre4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 316, Short.MAX_VALUE)
                .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Paramètres", panelParam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnulerActionPerformed

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
       //prend une photo
        
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnuler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butAnnuler2ActionPerformed

    private void butAnnuler3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butAnnuler3ActionPerformed

    private void labImaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labImaMouseClicked
        labIma.setIcon(null);
        fileChoose.setVisible(true);
    }//GEN-LAST:event_labImaMouseClicked

    private void fileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseActionPerformed
        fileChoose.setVisible(false);
        File selection = fileChoose.getSelectedFile();
        fileChoose.setSelectedFile(null);
        String completeFileName = selection.getAbsolutePath();

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(completeFileName).getScaledInstance(280, 280, Image.SCALE_DEFAULT));
        labIma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labIma.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        labIma.setIcon(icon);
    }//GEN-LAST:event_fileChooseActionPerformed

    private void butAnnuler4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresConnectionView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butAnnuler2;
    private javax.swing.JButton butAnnuler3;
    private javax.swing.JButton butAnnuler4;
    private javax.swing.JButton butValider;
    private javax.swing.JFileChooser fileChoose;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labIma;
    private javax.swing.JLabel labTitre1;
    private javax.swing.JLabel labTitre2;
    private javax.swing.JLabel labTitre3;
    private javax.swing.JLabel labTitre4;
    private javax.swing.JPanel panelAjout;
    private javax.swing.JPanel panelModif;
    private javax.swing.JPanel panelParam;
    private javax.swing.JPanel panelRecherche;
    // End of variables declaration//GEN-END:variables
}
