/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projetreconnaissancefaciale.Vues;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import projetreconnaissancefaciale.Controleurs.ParamUserHandler;

/**
 *
 * @author Alexis
 */
public class ApresConnectionView extends javax.swing.JFrame {

    /**
     * Creates new form ApresConnectionView
     */
    public ApresConnectionView() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelProfil = new javax.swing.JPanel();
        labTitre5 = new javax.swing.JLabel();
        labProfilNom = new javax.swing.JLabel();
        labProfilDateNaiss = new javax.swing.JLabel();
        labProfilInfo = new javax.swing.JLabel();
        labProfilImage = new javax.swing.JLabel();
        labProfilVille = new javax.swing.JLabel();
        labProfilPays = new javax.swing.JLabel();
        panelRecherche = new javax.swing.JPanel();
        labTitre3 = new javax.swing.JLabel();
        butAnnuler3 = new javax.swing.JButton();
        fileChooseRecherche = new javax.swing.JFileChooser();
        labImaRecherche = new javax.swing.JLabel();
        butValider1 = new javax.swing.JButton();
        panelAjout = new javax.swing.JPanel();
        labTitre1 = new javax.swing.JLabel();
        butAnnuler = new javax.swing.JButton();
        butValider = new javax.swing.JButton();
        panelModif = new javax.swing.JPanel();
        labTitre2 = new javax.swing.JLabel();
        fileChoose = new javax.swing.JFileChooser();
        labIma = new javax.swing.JLabel();
        butAnnuler4 = new javax.swing.JButton();
        butValider2 = new javax.swing.JButton();
        panelParam = new javax.swing.JPanel();
        labTitre4 = new javax.swing.JLabel();
        butAnnuler2 = new javax.swing.JButton();
        butValider3 = new javax.swing.JButton();
        labNom = new javax.swing.JLabel();
        labPrenom = new javax.swing.JLabel();
        labMDP1 = new javax.swing.JLabel();
        labMDP2 = new javax.swing.JLabel();
        labMDP3 = new javax.swing.JLabel();
        textNom = new javax.swing.JTextField();
        textPrenom = new javax.swing.JTextField();
        textMDP1 = new javax.swing.JPasswordField();
        textMDP3 = new javax.swing.JPasswordField();
        textMDP2 = new javax.swing.JPasswordField();
        labParamDateNaiss = new javax.swing.JLabel();
        textParamDateNaiss = new com.toedter.calendar.JDateChooser();
        labParamVille = new javax.swing.JLabel();
        labParamPays = new javax.swing.JLabel();
        textParamVille = new javax.swing.JTextField();
        textParamPays = new javax.swing.JTextField();
        labParamInfo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textParamInfo = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(570, 463));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        labTitre5.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre5.setForeground(new java.awt.Color(62, 96, 111));
        labTitre5.setText("RecoFace");

        labProfilNom.setText("Bienvenue Nom Prenom");

        labProfilDateNaiss.setText("Né(e) le :  ");

        labProfilInfo.setText("Informations :");

        labProfilVille.setText("Ville :");

        labProfilPays.setText("Pays :");

        javax.swing.GroupLayout panelProfilLayout = new javax.swing.GroupLayout(panelProfil);
        panelProfil.setLayout(panelProfilLayout);
        panelProfilLayout.setHorizontalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labProfilInfo)
                            .addComponent(labProfilDateNaiss)
                            .addComponent(labProfilVille)
                            .addComponent(labProfilPays)))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(labProfilImage))
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTitre5)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfilLayout.createSequentialGroup()
                                .addComponent(labProfilNom)
                                .addGap(25, 25, 25)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        panelProfilLayout.setVerticalGroup(
            panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilLayout.createSequentialGroup()
                .addComponent(labTitre5)
                .addGap(18, 18, 18)
                .addComponent(labProfilNom)
                .addGap(15, 15, 15)
                .addGroup(panelProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labProfilInfo)
                    .addGroup(panelProfilLayout.createSequentialGroup()
                        .addComponent(labProfilDateNaiss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labProfilVille)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labProfilPays)
                        .addGap(23, 23, 23)
                        .addComponent(labProfilImage)))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mon Profil", panelProfil);

        labTitre3.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre3.setForeground(new java.awt.Color(62, 96, 111));
        labTitre3.setText("RecoFace");

        butAnnuler3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler3ActionPerformed(evt);
            }
        });

        fileChooseRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseRechercheActionPerformed(evt);
            }
        });

        labImaRecherche.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labImaRechercheMouseClicked(evt);
            }
        });

        butValider1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRechercheLayout = new javax.swing.GroupLayout(panelRecherche);
        panelRecherche.setLayout(panelRechercheLayout);
        panelRechercheLayout.setHorizontalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(labImaRecherche)
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRechercheLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTitre3)
                .addGap(181, 181, 181))
            .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRechercheLayout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(fileChooseRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        panelRechercheLayout.setVerticalGroup(
            panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRechercheLayout.createSequentialGroup()
                .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRechercheLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValider1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRechercheLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(labImaRecherche)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(butAnnuler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRechercheLayout.createSequentialGroup()
                        .addComponent(labTitre3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelRechercheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelRechercheLayout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(fileChooseRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Rechercher un utilisateur", panelRecherche);

        panelAjout.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelAjout.setPreferredSize(new java.awt.Dimension(600, 475));

        labTitre1.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre1.setForeground(new java.awt.Color(62, 96, 111));
        labTitre1.setText("RecoFace");

        butAnnuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnulerActionPerformed(evt);
            }
        });

        butValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValiderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAjoutLayout = new javax.swing.GroupLayout(panelAjout);
        panelAjout.setLayout(panelAjoutLayout);
        panelAjoutLayout.setHorizontalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAjoutLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(labTitre1)
                .addGap(178, 178, 178))
        );
        panelAjoutLayout.setVerticalGroup(
            panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAjoutLayout.createSequentialGroup()
                .addComponent(labTitre1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addGroup(panelAjoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butValider, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Prendre une photo", panelAjout);

        panelModif.setPreferredSize(new java.awt.Dimension(504, 445));

        labTitre2.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre2.setForeground(new java.awt.Color(62, 96, 111));
        labTitre2.setText("RecoFace");

        fileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseActionPerformed(evt);
            }
        });

        labIma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labImaMouseClicked(evt);
            }
        });

        butAnnuler4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler4ActionPerformed(evt);
            }
        });

        butValider2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelModifLayout = new javax.swing.GroupLayout(panelModif);
        panelModif.setLayout(panelModifLayout);
        panelModifLayout.setHorizontalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butValider2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModifLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTitre2)
                .addGap(179, 179, 179))
            .addGroup(panelModifLayout.createSequentialGroup()
                .addGroup(panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(labIma)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        panelModifLayout.setVerticalGroup(
            panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelModifLayout.createSequentialGroup()
                .addGroup(panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(butValider2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelModifLayout.createSequentialGroup()
                        .addGroup(panelModifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelModifLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(labIma))
                            .addComponent(labTitre2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fileChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butAnnuler4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Modification de photo", panelModif);

        labTitre4.setFont(new java.awt.Font("Chiller", 1, 48)); // NOI18N
        labTitre4.setForeground(new java.awt.Color(62, 96, 111));
        labTitre4.setText("RecoFace");

        butAnnuler2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/gtk-cancel.png"))); // NOI18N
        butAnnuler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAnnuler2ActionPerformed(evt);
            }
        });

        butValider3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetreconnaissancefaciale/Vues/Images/ip_icon_02_Ok.png"))); // NOI18N
        butValider3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butValider3ActionPerformed(evt);
            }
        });

        labNom.setText("Nom :");

        labPrenom.setText("Prénom :");

        labMDP1.setText("Ancien mot de passe :");

        labMDP2.setText("Nouveau mot de passe :");

        labMDP3.setText("Nouveau mot de passe :");

        labParamDateNaiss.setText("Date de Naissance :");

        labParamVille.setText("Ville :");

        labParamPays.setText("Pays :");

        labParamInfo.setText("Informations :");

        textParamInfo.setColumns(20);
        textParamInfo.setRows(5);
        jScrollPane1.setViewportView(textParamInfo);

        javax.swing.GroupLayout panelParamLayout = new javax.swing.GroupLayout(panelParam);
        panelParam.setLayout(panelParamLayout);
        panelParamLayout.setHorizontalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValider3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labTitre4)
                            .addGroup(panelParamLayout.createSequentialGroup()
                                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panelParamLayout.createSequentialGroup()
                                        .addComponent(labParamInfo)
                                        .addGap(38, 38, 38)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelParamLayout.createSequentialGroup()
                                        .addComponent(labNom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labPrenom, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelParamLayout.createSequentialGroup()
                                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labParamDateNaiss)
                                            .addComponent(labParamVille)
                                            .addComponent(labParamPays))
                                        .addGap(84, 84, 84)
                                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textPrenom)
                                            .addComponent(textParamDateNaiss, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                            .addComponent(textParamVille)
                                            .addComponent(textParamPays))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labMDP2)
                                        .addComponent(labMDP3))
                                    .addComponent(labMDP1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textMDP1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMDP2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textMDP3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelParamLayout.setVerticalGroup(
            panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelParamLayout.createSequentialGroup()
                .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addComponent(labTitre4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNom)
                            .addComponent(textNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labMDP1)
                            .addComponent(textMDP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labPrenom)
                            .addComponent(textPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labMDP2)
                            .addComponent(textMDP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labMDP3)
                                .addComponent(textMDP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textParamDateNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labParamDateNaiss))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamVille)
                            .addComponent(textParamVille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamPays)
                            .addComponent(textParamPays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(panelParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labParamInfo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(butAnnuler2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelParamLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butValider3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        jTabbedPane1.addTab("Paramètres", panelParam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnulerActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnulerActionPerformed

    private void butValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValiderActionPerformed
        //prend une photo
    }//GEN-LAST:event_butValiderActionPerformed

    private void butAnnuler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler2ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_butAnnuler2ActionPerformed

    private void butAnnuler3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler3ActionPerformed

    private void labImaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labImaMouseClicked
        labIma.setIcon(null);
        fileChoose.setVisible(true);
    }//GEN-LAST:event_labImaMouseClicked

    private void fileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseActionPerformed
        fileChoose.setVisible(false);
        File selection = fileChoose.getSelectedFile();
        fileChoose.setSelectedFile(null);
        String completeFileName = selection.getAbsolutePath();

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(completeFileName).getScaledInstance(280, 280, Image.SCALE_DEFAULT));
        labIma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labIma.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        labIma.setIcon(icon);
    }//GEN-LAST:event_fileChooseActionPerformed

    private void butAnnuler4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAnnuler4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_butAnnuler4ActionPerformed

    private void fileChooseRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseRechercheActionPerformed
        fileChooseRecherche.setVisible(false);
        File selection = fileChooseRecherche.getSelectedFile();
        fileChooseRecherche.setSelectedFile(null);
        String completeFileName = selection.getAbsolutePath();

        ImageIcon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(completeFileName).getScaledInstance(280, 280, Image.SCALE_DEFAULT));
        labImaRecherche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labImaRecherche.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        labImaRecherche.setIcon(icon);
    }//GEN-LAST:event_fileChooseRechercheActionPerformed

    private void labImaRechercheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labImaRechercheMouseClicked
        labImaRecherche.setIcon(null);
        fileChooseRecherche.setVisible(true);
    }//GEN-LAST:event_labImaRechercheMouseClicked

    private void butValider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butValider1ActionPerformed

    private void butValider2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butValider2ActionPerformed

    private void butValider3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butValider3ActionPerformed
        try {
            ParamUserHandler.Valider(textMDP1.toString(), textMDP2.toString(), textMDP3.toString());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(ApresConnectionView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_butValider3ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        //ParamUserHandler.RechercheInfoUser();
        textNom.setText(ParamUserHandler.getUserNom());
        textPrenom.setText(ParamUserHandler.getUserPrenom());
      //  textParamDateNaiss.setText(ParamUserHandler.getUserDateNaiss());
        textParamVille.setText(ParamUserHandler.getUserVille());
        textParamPays.setText(ParamUserHandler.getUserPays());
        textParamInfo.setText(ParamUserHandler.getUserInfo());
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        ParamUserHandler.RechercheInfoUser();
        labProfilNom.setText("");
        labProfilNom.setText("Bienvenue " + ParamUserHandler.getUserPrenom().toString() + " " + ParamUserHandler.getUserNom().toString().toUpperCase());
        labProfilDateNaiss.setText("");
        labProfilDateNaiss.setText("Né(e) le : "+ParamUserHandler.getUserDateNaiss().toString());
        labProfilVille.setText("");
        labProfilVille.setText("Ville : "+ParamUserHandler.getUserVille().toString());
        labProfilPays.setText("");
        labProfilPays.setText("Pays : "+ParamUserHandler.getUserPays().toString().toUpperCase());
        labProfilInfo.setText("");
        labProfilInfo.setText("Informations : "+ParamUserHandler.getUserInfo().toString());
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApresConnectionView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApresConnectionView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAnnuler;
    private javax.swing.JButton butAnnuler2;
    private javax.swing.JButton butAnnuler3;
    private javax.swing.JButton butAnnuler4;
    private javax.swing.JButton butValider;
    private javax.swing.JButton butValider1;
    private javax.swing.JButton butValider2;
    private javax.swing.JButton butValider3;
    private javax.swing.JFileChooser fileChoose;
    private javax.swing.JFileChooser fileChooseRecherche;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labIma;
    private javax.swing.JLabel labImaRecherche;
    private javax.swing.JLabel labMDP1;
    private javax.swing.JLabel labMDP2;
    private javax.swing.JLabel labMDP3;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labParamDateNaiss;
    private javax.swing.JLabel labParamInfo;
    private javax.swing.JLabel labParamPays;
    private javax.swing.JLabel labParamVille;
    private javax.swing.JLabel labPrenom;
    private javax.swing.JLabel labProfilDateNaiss;
    private javax.swing.JLabel labProfilImage;
    private javax.swing.JLabel labProfilInfo;
    private javax.swing.JLabel labProfilNom;
    private javax.swing.JLabel labProfilPays;
    private javax.swing.JLabel labProfilVille;
    private javax.swing.JLabel labTitre1;
    private javax.swing.JLabel labTitre2;
    private javax.swing.JLabel labTitre3;
    private javax.swing.JLabel labTitre4;
    private javax.swing.JLabel labTitre5;
    private javax.swing.JPanel panelAjout;
    private javax.swing.JPanel panelModif;
    private javax.swing.JPanel panelParam;
    private javax.swing.JPanel panelProfil;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPasswordField textMDP1;
    private javax.swing.JPasswordField textMDP2;
    private javax.swing.JPasswordField textMDP3;
    private javax.swing.JTextField textNom;
    private com.toedter.calendar.JDateChooser textParamDateNaiss;
    private javax.swing.JTextArea textParamInfo;
    private javax.swing.JTextField textParamPays;
    private javax.swing.JTextField textParamVille;
    private javax.swing.JTextField textPrenom;
    // End of variables declaration//GEN-END:variables
}
